eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
   instance: 
   # 将ip注册到server
    prefer-ip-address: true
server:
  port: 8762

spring:
  application:
    # 指定注册应用名称
    name: service-helloworld

